### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by jeromelaban** [banditoth/maui-appleprivacy-vscode#1]
Nice work on this extension!

Dark theme support would be great:

![image](https://github.com/banditoth/maui-appleprivacy-vscode/assets/5839577/42ced964-a536-4203-a8c3-0b5f2719ca53)

Also it works great with Uno Platform apps :)

**Comment by banditoth** [comment]
Hey @jeromelaban , thanks for your feedback!

I will fix that soon!

**Comment by banditoth** [comment]
Closed as completed in 1.0.0
